#!/usr/bin/env bash

set -e

# Ensure JAVA_HOME is set
if [ -z "$JAVA_HOME" ]; then
    echo "JAVA_HOME is not set. Please set it to your Java installation path."
    exit 1
fi

rm -rf dist
mkdir dist
cd eclipse.jdt.ls/
JAVA_HOME=$JAVA_HOME ./mvnw clean verify -DskipTests

# Download lombok-edge.jar
Lombok_JAR_URL="https://projectlombok.org/lombok-edge.jar"
curl -L -o lombok-edge.jar "$Lombok_JAR_URL"

mv lombok-edge.jar org.eclipse.jdt.ls.product/target/repository/plugins

tar -czf ../dist/eclipse.jdt.ls.tar.gz -C ./org.eclipse.jdt.ls.product/target/repository .
