name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write 
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          maven: true

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          clean: false
          submodules: 'recursive'

      - name: Create tarball
        run: script/build

      - name: Upload tarball to workflow run if main branch
        uses: actions/upload-artifact@v4
        with:
          name: eclipse.jdt.ls.tar.gz
          path: dist/eclipse.jdt.ls.tar.gz

      - uses: softprops/action-gh-release@v1
        name: Upload binaries to release if release tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          draft: true
          files: dist/*
          overwrite: true
          body: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
